import defineBlocks from './definitions';
import defineGenerators from './generators';
import toolboxData from './toolbox.json';

export const visionModule = {
  definitions: defineBlocks,
  generators: defineGenerators,
  toolbox: toolboxData,
  i18n: {
    ko: {
      VISION: "AI 비전 (ESP32-S3)",
      START_PC_STREAM: "카메라 영상을 에디터로 전송하기",
      GET_PC_HAND_X: "에디터에서 찾은 손가락 X 좌표",
      GET_PC_HAND_Y: "에디터에서 찾은 손가락 Y 좌표",
      TT_START_PC_STREAM: "ESP32의 카메라 영상을 PC로 전송하여 MediaPipe로 분석합니다.",
      TT_GET_PC_HAND: "PC에서 실시간으로 분석한 손가락 관절의 좌표값을 가져옵니다.",
      LOAD_TFLITE: "기기 내부 모델 로드하기",
      RUN_INFERENCE: "자체 AI 추론 실행하기",
      GET_INFERENCE_RESULT: "자체 AI 추론 결과 (클래스 ID)",
      TRACK_START: "비전 라인트랙 스트리밍 시작",
      TRACK_DIRECTION: "트랙 방향 (에디터 분석)",
      TRACK_DIRECTION_IS: "트랙 방향이 다음과 같은가:",
      TRACK_RAW_COUNT: "트랙 어두운 픽셀 수 (",
      TRACK_DIR_LEFT: "왼쪽",
      TRACK_DIR_CENTER: "가운데",
      TRACK_DIR_RIGHT: "오른쪽",
      TRACK_DIR_NONE: "없음",
      TT_TRACK_START: "에디터 AI가 카메라 영상의 하단을 픽셀 분석하여 라인 방향을 ESP32로 전송합니다.",
      TT_TRACK_DIRECTION: "에디터가 분석한 트랙 라인의 방향 문자열 (LEFT/CENTER/RIGHT/NONE)을 가져옵니다.",
      TT_TRACK_DIRECTION_IS: "에디터가 분석한 트랙 방향이 선택한 방향과 일치하는지 확인합니다.",
      TT_TRACK_RAW_COUNT: "에디터가 분석한 영역별 어두운 픽셀 수를 가져옵니다. 값이 클수록 트랙(검은 선)이 그 방향에 있습니다.",
      IS_HAND_IN_ZONE: "손가락 위치가 다음 영역에 있는가:",
      ZONE_LEFT: "왼쪽 영역 (Left)",
      ZONE_CENTER: "가운데 영역 (Center)",
      ZONE_RIGHT: "오른쪽 영역 (Right)",
      ZONE_TOP: "윗쪽 영역 (Top)",
      ZONE_BOTTOM: "아랫쪽 영역 (Bottom)",
      TT_IS_HAND_IN_ZONE: "에디터가 분석한 손가락의 위치가 지정한 가상 터치 영역 안에 있는지 확인합니다.",
      IS_DETECTED_CLASS_EQUAL: "인식된 사물 번호가 %1 인가?",
      TT_IS_DETECTED_CLASS_EQUAL: "기기 내장 AI 카메라가 감지한 사물의 클래스 번호가 일치하는지 확인합니다.",
      GET_CLASS_NAME_BY_INDEX: "사물 번호 %1 의 이름을",
      GET_CLASS_NAME_LIST: "다음 목록 %1 에서 찾기",
      TT_GET_CLASS_NAME_BY_INDEX: "쉼표로 이루어진 사물 이름 리스트에서 해당 사물 번호에 대응되는 텍스트를 가져옵니다. (예: 0 -> 가위, 1 -> 바위, 2 -> 보)"
    },
    en: {
      VISION: "AI Vision (ESP32-S3)",
      START_PC_STREAM: "Stream Camera to Editor",
      GET_PC_HAND_X: "Hand X from Editor",
      GET_PC_HAND_Y: "Hand Y from Editor",
      TT_START_PC_STREAM: "Send camera stream to PC for MediaPipe analysis.",
      TT_GET_PC_HAND: "Get the hand coordinates analyzed by the PC.",
      LOAD_TFLITE: "Load on-device TFLite model",
      RUN_INFERENCE: "Run on-device AI inference",
      GET_INFERENCE_RESULT: "On-device AI Result (Class ID)",
      TRACK_START: "Start Vision Line Track Stream",
      TRACK_DIRECTION: "Track Direction (Editor Analysis)",
      TRACK_DIRECTION_IS: "Is track direction:",
      TRACK_RAW_COUNT: "Dark pixel count in region (",
      TRACK_DIR_LEFT: "Left",
      TRACK_DIR_CENTER: "Center",
      TRACK_DIR_RIGHT: "Right",
      TRACK_DIR_NONE: "None",
      TT_TRACK_START: "Editor AI analyzes the bottom of the frame pixel-by-pixel and sends track direction to ESP32.",
      TT_TRACK_DIRECTION: "Get the track direction string (LEFT/CENTER/RIGHT/NONE) analyzed by the editor.",
      TT_TRACK_DIRECTION_IS: "Check if the editor-analyzed track direction matches the selected direction.",
      TT_TRACK_RAW_COUNT: "Get the raw dark pixel count for each region. Higher means more track line in that zone.",
      IS_HAND_IN_ZONE: "Is finger in zone:",
      ZONE_LEFT: "Left Zone",
      ZONE_CENTER: "Center Zone",
      ZONE_RIGHT: "Right Zone",
      ZONE_TOP: "Top Zone",
      ZONE_BOTTOM: "Bottom Zone",
      TT_IS_HAND_IN_ZONE: "Checks if the hand coordinates analyzed by the editor are inside the specified virtual zone.",
      IS_DETECTED_CLASS_EQUAL: "Is detected object number %1 ?",
      TT_IS_DETECTED_CLASS_EQUAL: "Checks if the class ID of the object detected by the device AI camera matches.",
      GET_CLASS_NAME_BY_INDEX: "Find name for object ID %1",
      GET_CLASS_NAME_LIST: "from list %1",
      TT_GET_CLASS_NAME_BY_INDEX: "Retrieves the name corresponding to the object ID from a comma-separated list of labels."
    }
  }
};
