# This file is part of espzero, automatically synced from
# https://github.com/roboticsware/espzero at revision 24cae2bc1c028458052675181e95f2a08fdf7481.
# Do not edit this file directly — run update_user_libs.py espzero instead.

"""
espzero/profiles/_base.py
Abstract base class for all board profiles.

Every board-specific profile inherits from BoardProfile and declares
its hardware constants (pin aliases, ADC settings, strapping pins, etc.).
The HAL and core logic read these constants at runtime so that no
board-specific code ever leaks into _core.py.
"""


class BoardProfile:
    """Abstract base class for all board profiles."""

    NAME = "unknown"        # Human-readable board name
    CHIP = "esp32"          # Chip family: esp32 / esp32s3 / esp32c3 / esp8266

    # ── Pin aliases ───────────────────────────────────────────────
    # Allows users to refer to pins by name (e.g. "internal", "led")
    # instead of raw GPIO numbers.
    PIN_ALIASES = {}

    # ── ADC settings ──────────────────────────────────────────────
    ADC_MAX_RAW = 4095      # 12-bit resolution (0–4095)
    ADC_SCALE   = 65535     # Target scale for picozero compatibility (read_u16)
    ADC_ATTEN   = None      # e.g. machine.ADC.ATTN_11DB; None = use firmware default
    ADC_VREF    = 3.3       # Maximum input voltage (matches attenuation setting)

    # ── PWM settings ──────────────────────────────────────────────
    PWM_DEFAULT_FREQ = 1000     # Default PWM frequency in Hz (Pico used 100 Hz)
    PWM_DUTY_MAX     = 65535    # Internal duty scale is always 16-bit
    SERVO_FREQ       = 50       # Standard servo frequency: 50 Hz (20 ms frame)

    # ── Built-in temperature sensor ───────────────────────────────
    INTERNAL_TEMP_AVAILABLE = False

    # ── Built-in LED type ─────────────────────────────────────────
    # "digital"  – standard GPIO LED (on/off)
    # "neopixel" – WS2812 RGB LED (e.g. ESP32-S3 DevKit, M5Stack ATOM)
    INTERNAL_LED_TYPE        = "digital"
    INTERNAL_LED_ACTIVE_HIGH = True

    # ── Boot strapping pins ───────────────────────────────────────
    # Connecting a button or switch to these pins may cause boot failures
    # or force the chip into download mode.
    STRAPPING_PINS = []     # Example: [0, 2, 5, 12, 15]

    # ── ADC2 pins (unavailable while WiFi is active) ──────────────
    ADC2_PINS = []          # Example: [0, 2, 4, 12, 13, 14, 15, 25, 26, 27]

    # ── Restricted pins (wired to internal flash — never use as GPIO) ──
    # Driving these pins will corrupt flash memory and hang the system.
    RESTRICTED_PINS = []    # Example: [6, 7, 8, 9, 10, 11]

    # ─────────────────────────────────────────────────────────────

    def resolve_pin(self, pin):
        """Resolve a string alias or integer to a GPIO number."""
        if isinstance(pin, str):
            if pin in self.PIN_ALIASES:
                return self.PIN_ALIASES[pin]
            raise ValueError(
                "Unknown pin alias '{}' for board '{}'. "
                "Available aliases: {}".format(pin, self.NAME, list(self.PIN_ALIASES.keys()))
            )
        return int(pin)

    def make_adc(self, gpio_num):
        """Create an ADC object for the given GPIO, applying attenuation if configured."""
        from machine import ADC, Pin
        adc = ADC(Pin(gpio_num))
        if self.ADC_ATTEN is not None:
            adc.atten(self.ADC_ATTEN)
        return adc

    def adc_read_u16(self, adc_obj):
        """Read raw 12-bit ADC value and scale it to 0–65535 for picozero compatibility."""
        raw = adc_obj.read()   # 0–4095
        return (raw * self.ADC_SCALE) // self.ADC_MAX_RAW
